export { default as Header } from './Header/Header.component';
export { default as TodoItem } from './TodoItem/TodoItem.component';
export { default as TodoInput } from './TodoInput/TodoInput.component';
export { default as TodoFilter } from './TodoFilter/TodoFilter.component';
export { default as TodoProgress } from './TodoProgress/TodoProgress.component';
export { default as TodoList } from './TodoList/TodoList.component';
export { default as Loader } from './Loader/Loader.component';
export { default as Modal } from './Modal/Modal.component';
export { default as ModalDelete } from './ModalDelete/ModalDelete.component';
export {default as ModalEdit} from './ModalEdit/ModalEdit.component';
